### ISSUE TITLE
Add extension name to "requires WSAL" notice

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/wsal-extension-example#3]
We need to add the extension name to this notice for https://github.com/WPWhiteSecurity/wp-security-audit-log-premium/issues/1599

![image](https://user-images.githubusercontent.com/59394454/108360555-48f0ee80-71e9-11eb-9127-860e877232e5.png)

Once updated, this needs pulling into each extension repo also

**Comment by martinkrcho** [comment]
I am closing this one as it will be handled by issue https://github.com/WPWhiteSecurity/wsal-extension-example/issues/6/.
